mysql:
  url: jdbc:mysql://localhost:3306/steward_activity
  username: root
  password: root

# è‡ªåŠ¨ç­¾åˆ°æ¨¡å¼
auto-mode: true

# QQæœºå™¨äººAPIåœ°å€
go-cqhttp: http://localhost:8080

# QQç¾¤
qq-group:
  message: 12345
  report: 54321

# å½“æ—¥åœ¨çº¿æ—¶é•¿æœ€é•¿
star-of-day:
  message: ğŸ‰æœ¬æ—¥ä¹‹æ˜Ÿ ğŸ‘‰ %s
  reward: 10000

# å½“æœˆç­¾åˆ°æ¬¡æ•°æœ€å¤š
star-of-month:
  message: ğŸ‰æœ¬æœˆä¹‹æ˜Ÿ ğŸ‘‰ %s
  reward: 50000

# æé†’å‘¨æœŸ, å•ä½: åˆ†
task-period: 5

# ç©å®¶å½“æ—¥ç¬¬ä¸€æ¬¡ç™»å½•æ˜¯å¦ç›´æ¥æ˜¾ç¤ºGUI
show-on-first-login: true

# è¡¥ç­¾æœºä¼š
chance: 2

# ç­¾åˆ°å¥–åŠ±
sign-reward: 50

# æœˆå†…å¤©æ•°å¥–åŠ±, å•ä½: å¤©
days-reward:
  - 2: 200
  - 3: 300

# å¤©å†…åœ¨çº¿æ—¶é•¿å¥–åŠ±, å•ä½: åˆ†
duration-reward:
  - 2: 200
  - 3: 300